### PR TITLE
Dependency updates, fixes in dC and Omega

### PR DESCRIPTION
**Pull request by enze-chen**

### CODE REVIEW

**Comment by enze-chen** [comment]
Some of the major changes (that I can remember):
- Compatibility with the most recent versions of dependencies, notably pymatgen.
- Error in dC matrix where antisites were counted as 0 instead of -1. This has now been fixed.
- Error in Omega potential in solute case where a previous shallow copy led to wrong results for Ni3Al. This has now been fixed.
- Reduced a redundant concentration equation in the SymPy solver for the solute case.
- Stylistic consistencies.

**Comment by mbkumar** [comment]
Thank you Enze!

**Comment by enze-chen** [comment]
Wow, thanks for the fast update Bharat! I opened another PR because I just caught a small error in one of the headers. Sorry about that.

**Comment by mbkumar** [comment]
l haven't looked at PyDII in years. Now I don't have time to critically look at your fixes due to lot of high priority projects. Hoping you are not introducing any new bugs.

**Comment by mbkumar** [comment]
Please checkout mbkumar/pydii for updated pydii and there is a new branch there that works for ternary systems in a nice way.
If you can consolidate all of them and push an update that would be great.

**Comment by enze-chen** [comment]
> Now I don't have time to critically look at your fixes due to lot of high priority projects. Hoping you are not introducing any new bugs.
Yes, I completely understand. These fixes were made because I was verifying the existing code against the previous benchmarks in the PyDII paper, as well as applying it to a new system, Ni3Al as I mentioned. Comparing Ni3Al with other models in the literature and other approaches by us, everything seems to be working as expected.

> there is a new branch there that works for ternary systems in a nice way.
If you can consolidate all of them and push an update that would be great.
This is really interesting! I'm not sure if I will have time to validate, but duly noted. Thanks.

**Pull request merged**
